import '@/styles/globals.css'
import Head from 'next/head'
import Layout from '../components/layout'
import { AuthProvider } from '/AuthContext';

export default function MyApp({ Component, pageProps }) {

  return (
    <Layout>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <AuthProvider>
        <Component {...pageProps} />
      </AuthProvider>
    </Layout>
  )
}
